### ISSUE TITLE
Destroy proxy layer at the end

### ISSUE THREAD

**Issue by timurnurutdinov** [marckrenn/framer-animateOnSpline#1]
If you run animation several times, there are some leftovers (Note, that I changed layer name from "." to "proxy" for more control): 
<img width="143" alt="screen shot 2017-11-09 at 12 32 21 pm" src="https://user-images.githubusercontent.com/3430880/32598180-144db950-c54a-11e7-8d54-cbfd656d581f.png">

**Comment by marckrenn** [comment]
I just pushed an update.

Could you verify if this fixes the abovementioned problem?

**Comment by timurnurutdinov** [comment]
It's awesome, thanks for this and animationEnd event!
