### ISSUE TITLE
Update to support SVG Layer & SVG Path

### ISSUE THREAD

**Issue by davo** [marckrenn/framer-animateOnSpline#3]
Hey @marckrenn I was wondering if you are interested in updating the module to support the native methods SVG Layer & SVG Path?

If you are interested I can commit time and give it a fair shot.

Let me know ;)

**Comment by marckrenn** [comment]
Of course I'm interested, but I'm not entirely sure if it's necessary? 😀 

Now that you can animate Layers along a spline _natively_, what exactly would this module do differently?

(I'm aware that this module works with dynamic controlpoints, but as long as `SVGPath`-controlpoints cannot be changed via code, you probably won't be able to do implement that anyway, right?!)

**Comment by davo** [comment]
Yeah, you are right about both things. My main driver was to reuse the control points in an updated setting.

Maybe an exploratory fork?

Thanks Marc!

**Comment by marckrenn** [comment]
> Maybe an exploratory fork?
Sounds good. If you think I could help you, just ping me. Always happy to help.
